# Generated by Django 6.0.5 on 2026-05-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo_cliente', models.CharField(choices=[('Persona', 'Persona'), ('Empresa', 'Empresa')], max_length=20)),
                ('departamento', models.CharField(choices=[('Managua', 'Managua'), ('León', 'León'), ('Granada', 'Granada'), ('Masaya', 'Masaya'), ('Carazo', 'Carazo'), ('Chinandega', 'Chinandega'), ('Estelí', 'Estelí'), ('Matagalpa', 'Matagalpa'), ('Jinotega', 'Jinotega'), ('Boaco', 'Boaco')], max_length=50)),
                ('servicio_interes', models.CharField(choices=[('Soporte técnico', 'Soporte técnico'), ('Mantenimiento preventivo', 'Mantenimiento preventivo'), ('Instalación de redes', 'Instalación de redes'), ('Reparación de equipos', 'Reparación de equipos'), ('Reparación de equipos', 'Reparación de equipos')], max_length=100)),
                ('comentario', models.TextField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
